#Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
my_list = [0,1,2,3,4,5]

In [4]:
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
print(type(my_list))

<class 'list'>


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
np.arange(10) # interval are between 0-10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange (4)

array([0, 1, 2, 3])

In [17]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [19]:
np.arange(5.5)

array([0., 1., 2., 3., 4., 5.])

In [20]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(7,12)

array([ 7,  8,  9, 10, 11])

In [22]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.arange(6,8,1)

array([6, 7])

In [24]:
np.arange(10,5)

array([], dtype=int32)

In [27]:
np.arange(-10,5)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [28]:
np.arange(0,100,5,3)

TypeError: Cannot interpret '3' as a data type

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros(5) #parameter tuning

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros(5,dtype = int) #hyperamater tuning

array([0, 0, 0, 0, 0])

In [32]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros(((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((2,2),dtype =int)

array([[0, 0],
       [0, 0]])

In [36]:
np.zeros((5,10),dtype =int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
np.ones((2,6),dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [42]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
rand(2,3) # rand is function

NameError: name 'rand' is not defined

In [49]:
random.rand(2,3) # random is module

NameError: name 'random' is not defined

In [50]:
np.random.rand(2,3) # np is package

array([[0.36784358, 0.36653655, 0.0564646 ],
       [0.14026747, 0.30045794, 0.88209272]])

In [52]:
np.random.rand(2,3)

array([[0.6098567 , 0.00439267, 0.85079039],
       [0.40124931, 0.78512578, 0.79082864]])

In [53]:
np.random.randint(2,3)

2

In [62]:
np.random.randint(2,8)

5

In [63]:
np.random.randint(1,20,4)

array([19,  7,  6,  4])

In [66]:
np.random.randint(2,6,(4,5))

array([[4, 2, 3, 5, 3],
       [2, 4, 2, 2, 4],
       [5, 5, 5, 4, 5],
       [2, 5, 3, 4, 2]])

In [68]:
np.random.randint(2,4,(2,3))

array([[3, 3, 2],
       [3, 3, 3]])

In [69]:
a = np.random.randint(10,40,(3,4))

In [70]:
a

array([[28, 25, 33, 34],
       [28, 18, 25, 35],
       [10, 34, 26, 39]])

In [ ]:
np.arange