#Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
my_list = [0,1,2,3,4,5]

In [4]:
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
print(type(my_list))

<class 'list'>


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
np.arange(10) # interval are between 0-10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange (4)

array([0, 1, 2, 3])

In [17]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [19]:
np.arange(5.5)

array([0., 1., 2., 3., 4., 5.])

In [20]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(7,12)

array([ 7,  8,  9, 10, 11])

In [22]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.arange(6,8,1)

array([6, 7])

In [24]:
np.arange(10,5)

array([], dtype=int32)

In [27]:
np.arange(-10,5)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [28]:
np.arange(0,100,5,3)

TypeError: Cannot interpret '3' as a data type

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros(5) #parameter tuning

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros(5,dtype = int) #hyperamater tuning

array([0, 0, 0, 0, 0])

In [32]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros(((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((2,2),dtype =int)

array([[0, 0],
       [0, 0]])

In [36]:
np.zeros((5,10),dtype =int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
np.ones((2,6),dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [42]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
rand(2,3) # rand is function

NameError: name 'rand' is not defined

In [49]:
random.rand(2,3) # random is module

NameError: name 'random' is not defined

In [50]:
np.random.rand(2,3) # np is package

array([[0.36784358, 0.36653655, 0.0564646 ],
       [0.14026747, 0.30045794, 0.88209272]])

In [52]:
np.random.rand(2,3)

array([[0.6098567 , 0.00439267, 0.85079039],
       [0.40124931, 0.78512578, 0.79082864]])

In [53]:
np.random.randint(2,3)

2

In [62]:
np.random.randint(2,8)

5

In [63]:
np.random.randint(1,20,4)

array([19,  7,  6,  4])

In [66]:
np.random.randint(2,6,(4,5))

array([[4, 2, 3, 5, 3],
       [2, 4, 2, 2, 4],
       [5, 5, 5, 4, 5],
       [2, 5, 3, 4, 2]])

In [68]:
np.random.randint(2,4,(2,3))

array([[3, 3, 2],
       [3, 3, 3]])

In [69]:
a = np.random.randint(10,40,(3,4))

In [70]:
a

array([[28, 25, 33, 34],
       [28, 18, 25, 35],
       [10, 34, 26, 39]])

In [2]:
b=np.random.randint(10,20,(5,4))

In [3]:
b

array([[11, 10, 17, 19],
       [19, 12, 13, 17],
       [15, 19, 15, 16],
       [19, 11, 17, 17],
       [11, 10, 17, 17]])

In [4]:
type(b)

numpy.ndarray

In [5]:
b[:]

array([[11, 10, 17, 19],
       [19, 12, 13, 17],
       [15, 19, 15, 16],
       [19, 11, 17, 17],
       [11, 10, 17, 17]])

In [8]:
b[1:3] #by default it print assigned row count 3 beacome 3-1 

array([[19, 12, 13, 17],
       [15, 19, 15, 16]])

In [9]:
b

array([[11, 10, 17, 19],
       [19, 12, 13, 17],
       [15, 19, 15, 16],
       [19, 11, 17, 17],
       [11, 10, 17, 17]])

In [14]:
b[1,3] # specific value satisfy the rows and column

17

In [15]:
b[2,3]

16

In [17]:
b[::-1] # reverse

array([[11, 10, 17, 17],
       [19, 11, 17, 17],
       [15, 19, 15, 16],
       [19, 12, 13, 17],
       [11, 10, 17, 19]])

In [18]:
b[::-2]

array([[11, 10, 17, 17],
       [15, 19, 15, 16],
       [11, 10, 17, 19]])

In [19]:
b[::-3]

array([[11, 10, 17, 17],
       [19, 12, 13, 17]])

In [20]:
b[::3]

array([[11, 10, 17, 19],
       [19, 11, 17, 17]])

#indexing in array

In [21]:
mat=np.arange(0,100).reshape(10,10)

In [22]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
row ,col =4,5

In [24]:
print(row)
print(col)

4
5


In [25]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat[row,col]# 4th row and 5th column value it will give

45

In [28]:
mat[4,5]

45

In [29]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
mat[0:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [31]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [35]:
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [36]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [38]:
mat[2:-3]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [39]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
mat[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [12, 13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77],
       [82, 83, 84, 85, 86, 87],
       [92, 93, 94, 95, 96, 97]])

In [42]:
mat[:,2:4]# before : is for row and after : is for column

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [43]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [44]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[1:2,3:4]

array([[13]])

In [46]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
mat[0:10:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [51]:
mat[:,0:10:8]

array([[ 0,  8],
       [10, 18],
       [20, 28],
       [30, 38],
       [40, 48],
       [50, 58],
       [60, 68],
       [70, 78],
       [80, 88],
       [90, 98]])

In [52]:
mat[:,0:10:4]

array([[ 0,  4,  8],
       [10, 14, 18],
       [20, 24, 28],
       [30, 34, 38],
       [40, 44, 48],
       [50, 54, 58],
       [60, 64, 68],
       [70, 74, 78],
       [80, 84, 88],
       [90, 94, 98]])

#masking filter

In [53]:
id(mat)

1843416016496

In [54]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [55]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [56]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [58]:
mat[mat==50]

array([50])

In [59]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])